services:
  - type: web
    name: maharaja-raffle-hicksville
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma db push --force-reset --accept-data-loss && npm run seed && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_PASSWORD
        value: admin123secure
      - key: DATABASE_URL
        fromDatabase:
          name: maharaja-raffle-hicksville-db
          property: connectionString

databases:
  - name: maharaja-raffle-hicksville-db
    plan: free
    ipAllowList: []